[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Série
monitor_speed = 115200
monitor_port = ${this.upload_port}

; (optionnel) upload un peu plus rapide sur ESP32
upload_speed = 921600

lib_deps = 
  adafruit/Adafruit PWM Servo Driver Library@^3
  adafruit/Adafruit BusIO@^1
